name: Absolutely No Machete Juggling
description: "Rod Hilton&#039;s rants about stuff he cares about way too much."
url: http://www.nomachetejuggling.com

markdown: redcarpet
highlighter: null

exclude: ['resume/', 'jekyll-cloudfiles-upload/', 'todo.txt', 'cloudfiles_upload.rb']

permalink: /:year/:month/:day/:title/

separator: "&raquo;"

kramdown: 
  use_coderay: false

# sass:
#   style: :compressed

category_dir: category
tag_dir: tag

paginate: 10
paginate_path: "page:num"