name: Absolutely No Machete Juggling
tagline: "Rod Hilton&#039;s rants about stuff he cares about way too much."

markdown: redcarpet
highlighter: null

exclude: ['resume/', 'todo.txt', 'cloudfiles_upload.rb']

permalink: /:year/:month/:day/:title/

separator: "&raquo;"

kramdown: 
  use_coderay: false

sass:
  style: :compressed

category_dir: category
