name: Absolutely No Machete Juggling
tagline: "Rod Hilton&#039;s rants about stuff he cares about way too much."

markdown: kramdown
highlighter: null

permalink: /:year/:month/:day/:title/

separator: "&raquo;"

kramdown: 
  toc_levels: "1,2,3" 

category_dir: category